# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComtoUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.Companys', verbose_name='\u516c\u53f8')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, verbose_name='\u7528\u6237\u8d26\u53f7')),
                ('name', models.CharField(max_length=45, verbose_name='\u59d3\u540d')),
                ('password', models.CharField(max_length=45, verbose_name='\u5bc6\u7801')),
                ('department', models.CharField(max_length=45, verbose_name='\u90e8\u95e8')),
                ('position', models.CharField(max_length=45, verbose_name='\u804c\u4f4d')),
                ('tel', models.CharField(max_length=45, verbose_name='\u7535\u8bdd')),
                ('email', models.CharField(max_length=45, verbose_name='\u90ae\u7bb1')),
                ('total_class', models.IntegerField(default=0, verbose_name='\u5b66\u4e60\u8bfe\u7a0b')),
                ('companyid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companys.Companys', verbose_name='\u516c\u53f8')),
            ],
            options={
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
        ),
        migrations.AddField(
            model_name='comtousers',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companys.Users', verbose_name='\u7528\u6237'),
        ),
    ]
