# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-18 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeinfo',
            old_name='examination',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='examination',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question', verbose_name='\u95ee\u9898'),
        ),
    ]
