# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='takeinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_user_id', to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='question',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Examination', verbose_name='\u95ee\u5377'),
        ),
        migrations.AddField(
            model_name='examination',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.CourseOld', verbose_name='\u8bfe\u7a0b'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='takeinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.TakeInfo'),
        ),
    ]
