# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-22 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20180421_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='is_random',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u968f\u673a'),
        ),
        migrations.AddField(
            model_name='examination',
            name='question_num',
            field=models.IntegerField(default=0, verbose_name='\u9898\u76ee\u6570\u91cf'),
        ),
    ]
