# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-18 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20180418_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='runinfo',
            new_name='takeinfo',
        ),
    ]
