# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-22 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20180422_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examination',
            old_name='question_num',
            new_name='question_count',
        ),
    ]
