# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nengli8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column=b'name', max_length=52, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7\xe5\x90\x8d')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
