# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacheres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('coursesAbstract', models.TextField(max_length=45, verbose_name='\u8bfe\u7a0b\u7b80\u4ecb')),
                ('cover', models.ImageField(upload_to=b'images/%Y/%m', verbose_name='\u5c01\u9762')),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacheres.Teacheres', verbose_name='\u8bb2\u5e08id')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
    ]
