# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-15 00:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe5\xad\x97')),
                ('desc', models.TextField(verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('detail', models.TextField(verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe8\xaf\xa6\xe6\x83\x85')),
                ('degree', models.CharField(choices=[(b'cj', b'\xe5\x88\x9d\xe7\xba\xa7'), (b'zj', b'\xe4\xb8\xad\xe7\xba\xa7'), (b'gj', b'\xe9\xab\x98\xe7\xba\xa7')], max_length=2, verbose_name=b'\xe9\x9a\xbe\xe5\xba\xa6')),
                ('learn_times', models.IntegerField(default=0, verbose_name=b'\xe5\xad\xa6\xe4\xb9\xa0\xe6\x97\xb6\xe9\x95\xbf(\xe5\x88\x86\xe9\x92\x9f\xe6\x95\xb0)')),
                ('students', models.IntegerField(default=0, verbose_name=b'\xe5\xad\xa6\xe4\xb9\xa0\xe4\xba\xba\xe6\x95\xb0')),
                ('fav_nums', models.IntegerField(default=0, verbose_name=b'\xe6\x94\xb6\xe8\x97\x8f\xe4\xba\xba\xe6\x95\xb0')),
                ('image', models.ImageField(upload_to=b'courses/%Y/%m', verbose_name=b'\xe5\xb0\x81\xe9\x9d\xa2\xe5\x9b\xbe')),
                ('click_nums', models.IntegerField(default=0, verbose_name=b'\xe7\x82\xb9\xe5\x87\xbb\xe6\x95\xb0')),
                ('is_banner', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe6\x98\xaf\xe8\xbd\xae\xe6\x92\xad\xe5\x9b\xbe')),
                ('category', models.CharField(default=b'\xe5\x90\x8e\xe7\xab\xaf', max_length=20, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe7\xb1\xbb\xe5\x88\xab')),
                ('tag', models.CharField(default=b'', max_length=10, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\xa0\x87\xe7\xad\xbe')),
                ('youneed_know', models.CharField(default=b'', max_length=300, verbose_name=b'\xe8\xaf\xbe\xe5\x89\x8d\xe9\xa1\xbb\xe7\x9f\xa5')),
                ('teacher_tell', models.CharField(default=b'', max_length=300, verbose_name=b'\xe8\x80\x81\xe5\xb8\x88\xe5\x91\x8a\xe8\xaf\x89\xe4\xbd\xa0\xe8\x83\xbd\xe5\xad\xa6\xe4\xbb\x80\xe4\xb9\x88')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('course_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x9c\xba\xe6\x9e\x84')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name=b'\xe8\xae\xb2\xe5\xb8\x88')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe8\xaf\xbe\xe4\xbb\xb6\xe5\x90\x8d')),
                ('download', models.FileField(upload_to=b'course/resource/%Y/%m', verbose_name=b'\xe8\xb5\x84\xe6\xba\x90\xe6\x96\x87\xe4\xbb\xb6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b\u8d44\u6e90',
                'verbose_name_plural': '\u8bfe\u7a0b\u8d44\u6e90',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82\xe5\x90\x8d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b')),
            ],
            options={
                'verbose_name': '\u7ae0\u8282',
                'verbose_name_plural': '\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe5\x90\x8d')),
                ('url', models.URLField(default=b'', verbose_name=b'\xe8\xae\xbf\xe9\x97\xae\xe5\x9c\xb0\xe5\x9d\x80')),
                ('learn_times', models.IntegerField(default=0, verbose_name=b'\xe8\xa7\x86\xe9\xa2\x91\xe6\x97\xb6\xe9\x95\xbf(\xe5\x88\x86\xe9\x92\x9f\xe6\x95\xb0)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82')),
            ],
            options={
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '\u8f6e\u64ad\u8bfe\u7a0b',
                'proxy': True,
                'verbose_name_plural': '\u8f6e\u64ad\u8bfe\u7a0b',
            },
            bases=('courses.course',),
        ),
    ]
