# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-05 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
    ]
