# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='EmailVerifyRecord',
        ),
    ]
