# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-03 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe5\x8f\x91\xe9\x80\x81\xe6\x97\xb6\xe9\x97\xb4'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[(b'register', b'\xe6\xb3\xa8\xe5\x86\x8c\xe9\x82\xae\xe7\xae\xb1'), (b'forget', b'\xe5\xbf\x98\xe8\xae\xb0\xe5\xaf\x86\xe7\xa0\x81'), (b'update_email', b'\xe4\xbf\xae\xe6\x94\xb9\xe9\x82\xae\xe7\xae\xb1')], max_length=18, verbose_name=b'\xe9\xaa\x8c\xe8\xaf\x81\xe7\xa0\x81\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
