# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacheres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45, verbose_name='\u6559\u5e08\u767b\u5f55\u540d')),
                ('password', models.CharField(max_length=45, verbose_name='\u5bc6\u7801')),
                ('name', models.CharField(max_length=45, verbose_name='\u6559\u5e08\u59d3\u540d')),
                ('email', models.CharField(max_length=45, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=45, verbose_name='\u624b\u673a')),
                ('weixin', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u5fae\u4fe1')),
                ('introduce', models.TextField(max_length=500, verbose_name='\u4ecb\u7ecd')),
            ],
            options={
                'verbose_name': '\u57f9\u8bad\u5e08',
                'verbose_name_plural': '\u57f9\u8bad\u5e08',
            },
        ),
    ]
