# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(max_length=45, verbose_name='\u516c\u53f8id')),
                ('coursesid', models.CharField(max_length=45, verbose_name='\u8bfe\u7a0bid')),
                ('schoolTime', models.DateTimeField(verbose_name='\u4e0a\u8bfe\u65f6\u95f4')),
                ('address', models.CharField(max_length=100, verbose_name='\u4e0a\u8bfe\u5730\u70b9')),
                ('state', models.BooleanField(max_length=1, verbose_name='\u72b6\u6001')),
                ('period', models.CharField(max_length=45, verbose_name='\u5468\u671f')),
                ('hour', models.IntegerField(default=0, verbose_name='\u5b66\u65f6')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7',
            },
        ),
    ]
