# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-15 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.IntegerField()),
                ('name', models.CharField(max_length=128, verbose_name='问卷标题')),
                ('question', models.IntegerField()),
                ('question_text', models.CharField(max_length=128, verbose_name='问题')),
                ('qsort', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('choice', models.IntegerField()),
                ('choice_text', models.CharField(max_length=128, verbose_name='选项')),
                ('csort', models.IntegerField()),
                ('sum', models.IntegerField()),
                ('percent', models.IntegerField()),
            ],
            options={
                'db_table': 'questionnaire_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.IntegerField()),
                ('choice', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortnum', models.IntegerField(default=1, verbose_name='序号')),
                ('text', models.CharField(max_length=128, verbose_name='选项')),
                ('tags', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Tags')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortnum', models.IntegerField(default=1, verbose_name='序号')),
                ('type', models.CharField(choices=[('radio', '单选'), ('checkbox', '多选'), ('star', '打星'), ('text', '问答')], max_length=32, verbose_name='题型')),
                ('text', models.CharField(max_length=128, verbose_name='问题')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标题')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('take_nums', models.IntegerField(default=0, verbose_name='参与人数')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
                'permissions': (('export', 'Can export questionnaire answers'), ('management', 'Management Tools')),
            },
        ),
        migrations.CreateModel(
            name='RunInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='问卷时间')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire', verbose_name='问卷')),
            ],
            options={
                'verbose_name': '记录',
                'verbose_name_plural': '记录',
            },
        ),
    ]
