# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-09 23:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': '\u9009\u9879', 'verbose_name_plural': '\u9009\u9879'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '\u95ee\u9898', 'verbose_name_plural': '\u95ee\u9898'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'permissions': (('export', 'Can export questionnaire answers'), ('management', 'Management Tools')), 'verbose_name': '\u95ee\u5377', 'verbose_name_plural': '\u95ee\u5377'},
        ),
        migrations.AlterModelOptions(
            name='questionset',
            options={'verbose_name': '\u95ee\u9898\u96c6', 'verbose_name_plural': '\u95ee\u9898\u96c6'},
        ),
        migrations.AlterModelOptions(
            name='runinfo',
            options={'verbose_name': '\u8fd0\u884c\u4fe1\u606f', 'verbose_name_plural': '\u8fd0\u884c\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='runinfohistory',
            options={'verbose_name': '\u5386\u53f2\u8bb0\u5f55', 'verbose_name_plural': '\u5386\u53f2\u8bb0\u5f55'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '\u8c03\u67e5\u8005', 'verbose_name_plural': '\u8c03\u67e5\u8005'},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='extra_cn',
            new_name='extra',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_cn',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='extra_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='footer_cn',
        ),
        migrations.RemoveField(
            model_name='question',
            name='footer_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_cn',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='text_cn',
        ),
        migrations.RemoveField(
            model_name='questionset',
            name='text_en',
        ),
        migrations.AddField(
            model_name='choice',
            name='text',
            field=models.TextField(default=datetime.datetime(2018, 3, 9, 23, 35, 13, 110000), verbose_name='Choice Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='footer',
            field=models.TextField(blank=True, help_text=b'Footer rendered below the question interpreted as textile', verbose_name='Footer'),
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='questionset',
            name='text',
            field=models.TextField(default=datetime.datetime(2018, 3, 9, 23, 35, 16, 454000), help_text=b"This is interpreted as Textile: <a href='http://en.wikipedia.org/wiki/Textile_%28markup_language%29' target='_blank'>http://en.wikipedia.org/wiki/Textile_(markup_language)</a>", verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='language',
            field=models.CharField(choices=[(b'en', b'English'), (b'cn', b'Chinese')], default=b'zh-hans', max_length=8, verbose_name='Language'),
        ),
    ]
