# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-15 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='runinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_user_id', to=settings.AUTH_USER_MODEL, verbose_name='问卷用户'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='runinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.RunInfo'),
        ),
        migrations.CreateModel(
            name='PublishedQuestionnaire',
            fields=[
            ],
            options={
                'verbose_name': '统计',
                'verbose_name_plural': '统计',
                'proxy': True,
            },
            bases=('questionnaire.questionnaire',),
        ),
    ]
