# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_course_id', to='nengli8.CourseOld', verbose_name='\u95ee\u5377'),
        ),
    ]
