# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-21 22:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[(b'choice', '\u5355\u9009'), (b'multi', '\u591a\u9009'), (b'star', '\u6253\u661f'), (b'ask', '\u95ee\u7b54')], default=datetime.datetime(2018, 3, 21, 22, 54, 28, 240000), max_length=32, verbose_name='Type of question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
