# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='sortnum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='sortnum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
