# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20180404_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runinfo',
            old_name='subject',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[(b'radio', '\u5355\u9009'), (b'checkbox', '\u591a\u9009'), (b'star', '\u6253\u661f'), (b'text', '\u95ee\u7b54')], max_length=32, verbose_name='\u9898\u578b'),
        ),
    ]
