# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20180326_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chice_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
