# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-09 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20180408_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_published',
            field=models.BooleanField(default=datetime.datetime(2018, 4, 9, 23, 20, 22, 591000), verbose_name='\u53d1\u5e03'),
            preserve_default=False,
        ),
    ]
