# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-26 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_question_chice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='sortnum',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='sortnum',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
