# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-10 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_questionnaire_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedQuestionnaire',
            fields=[
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u95ee\u5377',
                'proxy': True,
                'verbose_name_plural': '\u53d1\u5e03\u95ee\u5377',
            },
            bases=('questionnaire.questionnaire',),
        ),
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Choice'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
    ]
