# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-27 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20180326_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='sortnum',
            field=models.IntegerField(default=0),
        ),
    ]
