# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-10 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20180410_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'questionnaire_statistics',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='chice_text',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='take_nums',
            field=models.IntegerField(default=0, verbose_name='\u53c2\u4e0e\u4eba\u6570'),
        ),
    ]
