# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-10 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20180410_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publishedquestionnaire',
            options={'verbose_name': '\u7edf\u8ba1', 'verbose_name_plural': '\u7edf\u8ba1'},
        ),
    ]
