# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-10 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_auto_20180410_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.IntegerField(),
        ),
    ]
