# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-11 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20180410_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=128, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='runinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_user_id', to=settings.AUTH_USER_MODEL, verbose_name='\u95ee\u5377\u7528\u6237'),
        ),
    ]
